version: "3.8"

services:
  movie_catalog:
    container_name: movie_catalog
    hostname: movie_catalog
    build: .
    command: bash -c "
      python manage.py migrate
      && python manage.py crontab add
      && cron restart
      && python manage.py runserver 0.0.0.0:8000
      "
    restart: on-failure
    tty: true
    stdin_open: true
    volumes:
      - .:/app/
    ports:
      - 8000:8000

